server:
  port: 9090
  tomcat:
    max-threads: 500
spring:
  profiles:
    active: local
---
spring:
  application:
    name: business-api
  profiles: local
  cloud:
    circuitbreaker:
      hystrix:
        enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/   # Eureka 서버
    healthcheck:
      enabled: true     # 현재 상태 전파 설정정  instance:
    metadata-map:
      management.port: ${management.port:8081}
    status-page-url-path: /info            # 상태 정보 보에지 설정 필요시
    secure-health-check-url: /health       # 상태 체크