

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
server:
  port: 8762
spring:
  application:
    name: zull-gateway-1
  cloud:
    circuitbreaker:
      hystrix:
        enabled: false

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxTotalHttpConnections: 500
  MaxConnectionsPerHost: 500
