


spring:
  application:
    name: zull-gateway-1
# 파일 전송을 사용하는 겨우 설정 필요
# 파일 저송 크기 제한 설정
#  servlet:
#    multipart:
#      max-file-size: 128MB
#      max-request-size=128MB


server:
  port: 8762

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true


ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxTotalHttpConnections: 500
  MaxConnectionsPerHost: 500

zuul:
  # https://github.com/Netflix/Hystrix/wiki/configuration#allowMaximumSizeToDivergeFromCoreSize
  # thread default 10   / semaphore
  ribbon-isolation-strategy: thread

  host:
    max-per-route-connections: 100
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
    circuitBreaker:
      requestVolumeThreshold:  100   # 설정수 값만큼 요청이 들어온 경우만 circut open 여부 결정 함
      errorThresholdPercentage: 50  # requestVolumn값을 넘는 요청 중 설정 값이상 비율이 에러인 경우 circuit open
      sleepWindowInMilliseconds: 5
  threadpool:
    default:
      coreSize: 20
      maximumSize: 100
      keepAliveTimeMinutes: 1
      allowMaximumSizeToDivergeFromCoreSize: true
